### ISSUE TITLE
aws: InstanceType configuration does not have effect

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/robotest#62]
`InstanceType` attribute is not taken into account (default is used) when provisioning aws infrastructure with terraform.

Configuration file used:
```
report_dir: /tmp/robotest-reports
cluster_name: foo
aws:
    region: us-east-1
    key_pair: key
    instance_type: "m3.large"
    vpc: "Create new"
    key_path: /path/to/key.pem
    ssh_user: centos
    os: centos
    cluster_name: foo
onprem:
    script_path: /path/to/assets/terraform/aws
    nodes: 3
```
